on: [push]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Increment Git Tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Increment Git Tag
        uses: xanderstevenson/gtts-action@v1
        id: gtts-action
        with:
          version-type: patch
          
      - name: Get the new version
        run: echo "The new version is ${{ steps.gtts-action.outputs.new-version }}"
