name: Create MP3 on Push to developer-hub
on:
  push:
    # only runs when files in this path are changed
    paths:
      - developer-hub/**
env:
  DEVOPS_DIR: devops


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # checkout the repository content to github runner.
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.8 #install the python needed
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
       
      - name: List of the GitHub Actions environment variables on Windows
        run: env

      - id: file_changes # see which file changed in the push
        uses: trilom/file-changes-action@v1.2.3
        with:
          outout: ''
          fileOutput: ''
          
          
      - name: test

        run:    |
          echo '${{ steps.file_changes.outputs.files_modified}}'   
          
      - name: execute py script # run file
        env:
          TEST_VAR: ${{ steps.file_changes.outputs.files_modified}}
        run: |
          python3 action-text-2-mp3.py
          echo "$TEST_VAR"
      - name: Commit files # transfer the new files back into the repository
        run: |
          git config --local user.name "xanderstevenson"
          a = ${{ steps.file_changes.outputs.files_modified}}
          git add ${a%/*}/./mp3s
          git commit -m "Updating the repository, mp3 in the ./mp3s folder"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
